apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: aiops
data:
  Corefile: |
    aiops.test:53 {
      hosts {
        127.0.0.1 api.aiops.test
        127.0.0.1 grafana.aiops.test
        127.0.0.1 jaeger.aiops.test
        127.0.0.1 prometheus.aiops.test
        fallthrough
      }
      errors
      log
    }
    .:53 {
      forward . /etc/resolv.conf
      cache 30
      errors
      health
    }
