apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: aiops
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxUnavailable: 1, maxSurge: 1}
  template:
    spec:
      containers:
      - name: auth-service
        image: auth-service:v0.1.2
        imagePullPolicy: Never
        env:
        - {name: APP_VERSION, value: "0.1.2"}
        readinessProbe: {httpGet: {path: /health, port: 8000}, initialDelaySeconds: 5, periodSeconds: 10}
        livenessProbe: {httpGet: {path: /health, port: 8000}, initialDelaySeconds: 15, periodSeconds: 15}
        resources:
          requests: {cpu: 50m, memory: 64Mi}
          limits: {cpu: 300m, memory: 256Mi}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector: {matchLabels: {app: auth-service}}
